{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.0.1.jar",
          "url": "builder-test-api-8.0.1.jar",
          "size": 15193,
          "sha512": "67bb6b6e0b9b7f39927d3c58bf2c3dd2163cebbdee5b4a9cbe63d5395e045442be0576da53852a45ca752466ba797ceea12f16b0dfed5d7b08d7e7a1a9b1f793",
          "sha256": "83a4f40a339209404c83600f604ab524e22ba4c49ccf2c4796783f278cead7c4",
          "sha1": "bab1fa038032559a9059c14e57b9ac8e1a4ece05",
          "md5": "1b4a1440a5194ec1ef06f4965019afed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.0.1.jar",
          "url": "builder-test-api-8.0.1.jar",
          "size": 15193,
          "sha512": "67bb6b6e0b9b7f39927d3c58bf2c3dd2163cebbdee5b4a9cbe63d5395e045442be0576da53852a45ca752466ba797ceea12f16b0dfed5d7b08d7e7a1a9b1f793",
          "sha256": "83a4f40a339209404c83600f604ab524e22ba4c49ccf2c4796783f278cead7c4",
          "sha1": "bab1fa038032559a9059c14e57b9ac8e1a4ece05",
          "md5": "1b4a1440a5194ec1ef06f4965019afed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.0.1-javadoc.jar",
          "url": "builder-test-api-8.0.1-javadoc.jar",
          "size": 116771,
          "sha512": "ae3d1b16da96dcd042b1561c34e08b8d578e9ebf12baeeee0a1e67cbb9d279ac9a917bb10cc545369a204c7e636a4d738638c3e491749d01b1202572f940ed10",
          "sha256": "c6497675b3affd697f9bfd29bdaf02da6edc46e7416c27f1d7f9e79bba350f28",
          "sha1": "4a7ecee675c9d96cff00b52b9142ebcb6138695a",
          "md5": "96b02668ca512bc09e36f550fad7bab4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.0.1-sources.jar",
          "url": "builder-test-api-8.0.1-sources.jar",
          "size": 13707,
          "sha512": "5379cb1c59c11f411f1c1d5af663e40466c92c8ef38f29d42bb76e59179d4802984c21a11f25cf82404ac87f24c60fca9e7a2931cfad3dd31fabd4e7b0a66406",
          "sha256": "8a4396dd4b1514bdb39c9c9382dc5a2af5f1ef5b7f35abe9b4ec9931fb0ae889",
          "sha1": "e6fb69948534c36008f8b43d497aba28095136b3",
          "md5": "c5e564231f9f9fd27b3e142e56a44faa"
        }
      ]
    }
  ]
}
