{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.0.1.jar",
          "url": "gradle-settings-api-8.0.1.jar",
          "size": 10051,
          "sha512": "63fd3fa323dea312eb2e2193348b53d0f2045be4f5c67daa9293c7fde825266c4dbfd17348d9498763473326f5ec48d3baa8b5ed8ef4b37fce06f64dc510811e",
          "sha256": "f584372e3d8ebc58884074d26583d42c47e0fc2c7e0fbfaacacda405da203420",
          "sha1": "95f0cc14304cc9ff210511b99618dbe6e106148d",
          "md5": "bd1ae354ff8c89c13754b225db62fde1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.0.1.jar",
          "url": "gradle-settings-api-8.0.1.jar",
          "size": 10051,
          "sha512": "63fd3fa323dea312eb2e2193348b53d0f2045be4f5c67daa9293c7fde825266c4dbfd17348d9498763473326f5ec48d3baa8b5ed8ef4b37fce06f64dc510811e",
          "sha256": "f584372e3d8ebc58884074d26583d42c47e0fc2c7e0fbfaacacda405da203420",
          "sha1": "95f0cc14304cc9ff210511b99618dbe6e106148d",
          "md5": "bd1ae354ff8c89c13754b225db62fde1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.0.1-javadoc.jar",
          "url": "gradle-settings-api-8.0.1-javadoc.jar",
          "size": 261,
          "sha512": "fba47acced2322c9f8c9d1c46860d06968f04d3caa6d9d9eb7afd3cc9d59bec61fb207ed23a4cda37b55b67a8eb9486fcf4caa5e3fbf36453d93d348740003c8",
          "sha256": "aee97556b8cb8c720e1e6aac9f7a0191c0d9b3cc97631c730232e6c9bf0ac2c9",
          "sha1": "46392dcf3ba32b0b464bdb82ba4414165874abf0",
          "md5": "6ef5b3644010ff1c89c5907d326ca7ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.0.1-sources.jar",
          "url": "gradle-settings-api-8.0.1-sources.jar",
          "size": 9475,
          "sha512": "6b4dd66bf1f659c27145932e72e54db752c7106b8d8ed4be6f027e7432ae2f1114aa58f24e95bc0474f8fac80a263562aebb53ebf84a4b4bdee01c66f510eae4",
          "sha256": "e4b2ab2795a48a36d9e689c8d56de15e74539b836d898d28180f4236513710b5",
          "sha1": "bd10cbd32edda077a511e61a61a982263c31f302",
          "md5": "232b48a95355e1b7fe982cb72685c23b"
        }
      ]
    }
  ]
}
