{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.0.1.jar",
          "url": "builder-8.0.1.jar",
          "size": 11296814,
          "sha512": "6545a5d3fb9a88c5f2554865ab5405f1f541dff5f76510f82a125b7a9cff8be615a856d974c2305f3c0dcc086a9876a231ebec110ce1615f792ea66b2df75470",
          "sha256": "536edbc3896b63be101580b3d78cb73139d4c5705aa09346d5b0b2d8f4f9d614",
          "sha1": "f96b119448ee31ff48853714638012e3fc334886",
          "md5": "9c99165a928c8f2bed96684e4ecced24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.0.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.0.1.jar",
          "url": "builder-8.0.1.jar",
          "size": 11296814,
          "sha512": "6545a5d3fb9a88c5f2554865ab5405f1f541dff5f76510f82a125b7a9cff8be615a856d974c2305f3c0dcc086a9876a231ebec110ce1615f792ea66b2df75470",
          "sha256": "536edbc3896b63be101580b3d78cb73139d4c5705aa09346d5b0b2d8f4f9d614",
          "sha1": "f96b119448ee31ff48853714638012e3fc334886",
          "md5": "9c99165a928c8f2bed96684e4ecced24"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.0.1-javadoc.jar",
          "url": "builder-8.0.1-javadoc.jar",
          "size": 400519,
          "sha512": "d4155fdc48d656099016257cc37d27debaf909613fdd46cfae030dda2d955ba94e692de3333205a7b0337bfd90e09619cc5a82f677bdf7827f92cd562cb2683d",
          "sha256": "8edea32a706a2ec711e71348e357d6103e0df3bc0ef0e0c91c5e522b68110188",
          "sha1": "81fee4ab6635e0282f513ad3fda542b2a8735863",
          "md5": "61ea085c4712193cff76617bbbe81b37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.0.1-sources.jar",
          "url": "builder-8.0.1-sources.jar",
          "size": 281867,
          "sha512": "2e080383c1f4f39effe39d076c2c194974f4756af89e1e98b2d5647c15edb6e88fb2960e35956729b29fa8a5daf0494de97be59fa89640db2e4f0374bc85bfa1",
          "sha256": "9be50ed33cb4d4cb9b6d0eeba485889da26c4ce42c2e282c7e9375f28b08f975",
          "sha1": "67b621ac47ec458037423a100c6fb735522ce2c2",
          "md5": "4ac4b8d58499d3bef600ce49201051cb"
        }
      ]
    }
  ]
}
